#!/bin/bash

# retrieving current working directory
CWD=`pwd`
MAIN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# go to main project dir
cd $MAIN_DIR/../../
# running format and check

mvn fmt:format && git add .
mvn checkstyle::check

if [ $? -ne 0 ]; then
  # go back to current working dir
  cd $CWD
  exit 1
fi

# go back to current working dir
cd $CWD
